# @package _global_

total_timesteps: 50_000_000
num_epochs: 12
num_eval_steps: 0

actor_head:
  _target_: memorax.networks.heads.Gaussian
  action_dim: ${get_action_dim:${environment}}
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
    scale: 0.01

algorithm:
  num_envs: 4096
  num_steps: 8
  gae_lambda: 0.95
  num_minibatches: 32
  update_epochs: 4
  normalize_advantage: True
  clip_coefficient: 0.2
  clip_value_loss: False
  entropy_coefficient: 0.0
  target_kl: 0.01

environment:
  wrappers:
    - _target_: memorax.utils.wrappers.ClipActionWrapper
