# @package _global_

defaults:
  - /torso: mlp
  - /stack: llama

actor_head:
  _target_: memorax.networks.heads.Categorical
  action_dim: ${get_action_dim:${environment}}

critic_head:
  _target_: memorax.networks.heads.VNetwork
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
    scale: 1.0

feature_extractor:
  _target_: memorax.networks.FeatureExtractor
  _convert_: object
  observation_extractor:
    _target_: flax.linen.Sequential
    layers:
      - _target_: flax.linen.Dense
        features: 256
      - _target_: flax.linen.relu
        _partial_: true

algorithm:
  _target_: memorax.algorithms.ACLambdaConfig
  name: ac_lambda
  num_envs: 32
  num_steps: 128
  trace_lambda: 0.95
  actor_lr: 3e-4
  critic_lr: 3e-4
  actor_kappa: 3.0
  critic_kappa: 2.0
  entropy_coefficient: 0.01
