# @package _global_
# https://github.com/mohmdelsayed/streaming-drl

defaults:
  - /head@actor_head: categorical
  - /head@critic_head: v_network

critic_head:
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
    scale: 1.0

feature_extractor:
  _target_: memorax.networks.FeatureExtractor
  _convert_: object
  observation_extractor:
    _target_: flax.linen.Sequential
    layers:
      - _target_: flax.linen.Dense
        features: 128
      - _target_: flax.linen.LayerNorm
        use_scale: false
        use_bias: false
      - _target_: flax.linen.leaky_relu
        _partial_: true
      - _target_: flax.linen.Dense
        features: 128
      - _target_: flax.linen.LayerNorm
        use_scale: false
        use_bias: false
      - _target_: flax.linen.leaky_relu
        _partial_: true

algorithm:
  _target_: memorax.algorithms.ACLambdaConfig
  name: ac_lambda
  num_envs: 1
  num_steps: 1
  trace_lambda: 0.8
  actor_lr: 1.0
  critic_lr: 1.0
  actor_kappa: 3.0
  critic_kappa: 2.0
  entropy_coefficient: 0.01
