# @package _global_

defaults:
  - /torso: mlp
  - /stack: llama

actor_head:
  _target_: memorax.networks.heads.Categorical
  action_dim: ${get_action_dim:${environment}}

critic_head:
  _target_: memorax.networks.heads.VNetwork
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
    scale: 1.0

feature_extractor:
  _target_: memorax.networks.FeatureExtractor
  _convert_: object
  observation_extractor:
    _target_: flax.linen.Sequential
    layers:
      - _target_: flax.linen.Dense
        features: 256
      - _target_: flax.linen.relu
        _partial_: true

optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 0.5
    - _target_: optax.adam
      learning_rate: 3e-4

algorithm:
  _target_: memorax.algorithms.MAPPOConfig
  name: mappo
  num_envs: 32
  num_steps: 128
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 4
  normalize_advantage: True
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.01
