# @package _global_

defaults:
  - /torso: mlp
  - /stack: llama

head:
  _target_: memorax.networks.heads.DiscreteQNetwork
  action_dim: ${get_action_dim:${environment}}

feature_extractor:
  _target_: memorax.networks.FeatureExtractor
  _convert_: object
  observation_extractor:
    _target_: flax.linen.Sequential
    layers:
      _target_: builtins.tuple
      _args_:
        - - _target_: flax.linen.Dense
            features: 256
          - _target_: flax.linen.relu

optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 1.0
    - _target_: optax.adam
      learning_rate: 3e-4

epsilon_schedule:
  _target_: optax.linear_schedule
  init_value: 1.0
  end_value: 0.05
  transition_steps: ${eval:'0.5 * ${total_timesteps}'}

algorithm:
  _target_: memorax.algorithms.PQNConfig
  name: pqn
  num_envs: 32
  num_steps: 128
  td_lambda: 0.95
  num_minibatches: 4
  update_epochs: 4

