# @package _global_

defaults:
  - /torso: mlp

algorithm:
  _target_: memorax.algorithms.R2D2Config
  name: r2d2
  num_envs: 32
  num_steps: 128
  tau: 1.0
  target_update_frequency: 500
  train_frequency: 4
  burn_in_length: 10
  sequence_length: 80
  n_step: 5
  priority_exponent: 0.9
  importance_sampling_exponent: 0.6
