# @package _global_
# https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/sac_continuous_action.py

defaults:
  - /head@actor_head: squashed_gaussian
  - /head@critic_head: twin_continuous_q_network

alpha:
  _target_: memorax.networks.heads.Alpha
  initial_alpha: 0.2

feature_extractor:
  _target_: memorax.networks.FeatureExtractor
  _convert_: object
  observation_extractor:
    _target_: flax.linen.Sequential
    layers:
      - _target_: flax.linen.Dense
        features: 256
      - _target_: flax.linen.relu
        _partial_: true
      - _target_: flax.linen.Dense
        features: 256
      - _target_: flax.linen.relu
        _partial_: true

actor_optimizer:
  _target_: optax.adam
  learning_rate: 3e-4

critic_optimizer:
  _target_: optax.adam
  learning_rate: 1e-3

alpha_optimizer:
  _target_: optax.adam
  learning_rate: 1e-3

sequence_length: 128

buffer:
  _target_: flashbax.make_trajectory_buffer
  add_batch_size: ${algorithm.num_envs}
  sample_batch_size: 256
  sample_sequence_length: ${sequence_length}
  period: 1
  min_length_time_axis: ${sequence_length}
  max_length_time_axis: 1_000_000

algorithm:
  _target_: memorax.algorithms.SACConfig
  name: sac
  num_envs: 1
  tau: 0.005
  train_frequency: 1
  target_update_frequency: 1
  target_entropy_scale: 1.0
  gradient_steps: 1
  burn_in_length: 0
