# @package _global_

total_timesteps: 50_000_000
num_epochs: 12
num_eval_steps: 0

actor_head:
  _target_: memorax.networks.heads.Gaussian
  action_dim: ${get_action_dim:${environment}}
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
    scale: 0.01

algorithm:
  num_envs: 4096
  num_steps: 8
  trace_lambda: 0.95
  actor_lr: 3e-4
  critic_lr: 3e-4
  entropy_coefficient: 0.0

environment:
  wrappers:
    - _target_: memorax.utils.wrappers.ClipActionWrapper
