# @package _global_
total_timesteps: 1_000_000_000
num_epochs: 30517

optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 0.5
    - _target_: optax.adam
      learning_rate: 3e-4
      eps: 1e-5

epsilon_schedule:
  _target_: optax.linear_schedule
  init_value: 1.0
  end_value: 0.005
  transition_steps: ${eval:'int(0.1 * (${total_timesteps} // ${algorithm.num_steps} // ${algorithm.num_envs}) * ${algorithm.num_minibatches} * ${algorithm.num_steps} * ${algorithm.num_envs})'}

algorithm:
  num_envs: 512
  num_steps: 64
  num_minibatches: 8
  update_epochs: 4
  td_lambda: 0.5
