# @package _global_

total_timesteps: 100_000_000
num_epochs: 1525
num_eval_steps: 100

epsilon_schedule:
  transition_steps: ${eval:'int(0.25 * ${total_timesteps})'}

algorithm:
  num_envs: 1024
  num_steps: 64
  num_minibatches: 16
  update_epochs: 4
  td_lambda: 0.95
