# @package _global_

optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 1.0
    - _target_: optax.adam
      learning_rate: 5e-4
      eps: 1e-5

epsilon_schedule:
  transition_steps: ${eval:'int(0.2 * ${total_timesteps})'}
