# @package _global_

total_timesteps: 10_000_000
num_train_steps: "${eval:'${algorithm.num_envs} * 1000'}"
num_eval_steps: 0

algorithm:
  num_envs: 256
  num_steps: 8
  tau: 0.005
  train_frequency: 1
  target_update_frequency: 1
  target_entropy_scale: 0.5
  gradient_steps: 1

environment:
  wrappers:
    - _target_: memorax.utils.wrappers.ClipActionWrapper
