total_timesteps: 10_000_000
num_epochs: 100
num_eval_steps: 0
seed: 0
checkpoint: false
num_seeds: 1
embeddings: oa

loggers: {}

defaults:
  - _self_
  - algorithm: ppo
  - environment: gymnax/cartpole
  - optional hyperparameters: ${cascading_fallback:${algorithm},${environment}}
  - logger: default
