# @package _global_

total_timesteps: 10_000_000
num_epochs: 2441

optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 0.5
    - _target_: optax.radam
      learning_rate:
        _target_: optax.linear_schedule
        init_value: 5e-5
        end_value: 5e-7
        transition_steps: ${eval:'${total_timesteps} // ${algorithm.num_steps} // ${algorithm.num_envs}'}

epsilon_schedule:
  transition_steps: ${eval:'int(0.25 * ${total_timesteps})'}

algorithm:
  num_envs: 32
  num_steps: 128
  tau: 1.0
  target_update_frequency: 500
  train_frequency: 4
