# @package _global_

total_timesteps: 15_000_000
num_epochs: 457
num_eval_steps: 832

optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 0.5
    - _target_: optax.adam
      learning_rate: 3e-4
      eps: 1e-5

epsilon_schedule:
  transition_steps: ${eval:'int(0.25 * ${total_timesteps})'}

algorithm:
  num_envs: 64
  num_steps: 512
  tau: 1.0
  target_update_frequency: 500
  train_frequency: 4
