# @package _global_

hidden_size: 32

observation_extractor:
  _target_: flax.linen.Dense
  features: 32

action_extractor:
  _target_: jax.nn.one_hot
  num_classes: ${get_action_dim:${environment}}
  _partial_: true

total_timesteps: 1_000_000
num_epochs: 250
num_eval_steps: 1_000

algorithm:
  num_envs: 4
  num_steps: 128
  gae_lambda: 0.7
  num_minibatches: 4
  update_epochs: 4
  normalize_advantage: True
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.01
