# @package _global_

hidden_size: 256

observation_extractor:
  _target_: flax.linen.Dense
  features: 256

action_extractor:
  _target_: flax.linen.Sequential
  layers:
    _target_: builtins.tuple
    _args_:
      - - _target_: flax.linen.Dense
            features: 64
          - _target_: flax.linen.relu
            _partial_: true

actor_head:
  _target_: memorax.networks.heads.Gaussian
  action_dim: ${get_action_dim:${environment}}
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
    scale: 0.01

total_timesteps: 50_000_000
num_epochs: 195
num_eval_steps: 0

algorithm:
  num_envs: 256
  num_steps: 128
  gae_lambda: 0.95
  num_minibatches: 16
  update_epochs: 4
  normalize_advantage: True
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.01
