# @package _global_

embeddings:
  - observation_embedding
  - action_embedding

torso:
  _target_: memorax.networks.sequence_models.Memoroid
  cell:
    _target_: salt.SALTLowRankCell
    head_dim: 16
    num_heads: 2
    low_rank_dim: 4
