name: SHM
_target_: memorax.networks.RNN
cell:
  _target_: memorax.networks.sequence_models.SHMCell
  features: 512
  output_features: 256
  kernel_init:
    _target_: flax.linen.initializers.lecun_normal
  bias_init:
    _target_: flax.linen.initializers.zeros_init
  param_dtype: float32
